on:
  issue_comment:
    types: [created]

name: PR commands
jobs:
  rebase:
    name: Rebase
    if: contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
